version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      REDIS_HOSTS: Index0:redis:6379:0,Index1:redis:6379:1
      TZ: JST-9
    depends_on:
      - redis
    ports:
      - '8081:8081'